### ISSUE TITLE
[1.20.1] Villager jobs functionality crashes the game

### ISSUE THREAD

**Issue by 630R63** [Reforged-Hub/radium-upstream#1]
### Version Information
radium-mc1.20-0.11.2
forge 47.1.44

### Expected Behavior
As advertised, I as expecting the villager job optimization code to work

### Actual Behavior
The game crashes

### Reproduction Steps
1. Launch the game using radium-mc1.20-0.11.2
2. Go near a village

### Other Information
Here is the crash log
[crash-2023-08-27_21.55.46-client.txt](https://github.com/Reforged-Hub/radium-upstream/files/12546856/crash-2023-08-27_21.55.46-client.txt)

**Comment by dima-dencep** [comment]
Fixed
