### ISSUE TITLE
[1.19.2] Dedicated server suddenly fails to start after installing Radium 

### ISSUE THREAD

**Issue by kawaiicakes** [Reforged-Hub/radium-upstream#11]
### Version
radium-0.8.2

This began immediately after installing Radium. Console log is attached.

### Crash Report File
https://paste.dedimc.io/osowafebez.kotlin

**Comment by embeddedt** [comment]
1.19.2 isn't supported anymore

**Comment by kawaiicakes** [comment]
It should be un[marked for compatibility](https://www.curseforge.com/minecraft/mc-mods/radium-reforged/files/3949703) w/ 1.19.2 then

**Comment by embeddedt** [comment]
No? The released version runs to my knowledge; it just has bugs.

**Comment by kawaiicakes** [comment]
Admittedly that was a kneejerk statement. I can try removing FerriteCore and seeing what happens some time.
