### ISSUE TITLE
[1.20.1] EntityShapeContextMixin breaks Bumblezone's Suspicious Pile of Pollen brushing

### ISSUE THREAD

**Issue by TelepathicGrunt** [Reforged-Hub/radium-upstream#13]
I have been tracking down an issue with Canary, Sodium, and Radium in regards to this mixin making unsafe assumptions and breaking my mod with its null itemstack in EntityShapeContext. 
https://github.com/Reforged-Hub/radium-upstream/blob/develop/src/main/java/me/jellysquid/mods/lithium/mixin/shapes/lazy_shape_context/EntityShapeContextMixin.java
https://github.com/TelepathicGrunt/Bumblezone/issues/299

The sodium issue report with more info: 
https://github.com/CaffeineMC/lithium-fabric/issues/498#issue-1990572965

I am working on a workaround by calling isHoldingItem early to force init the fields but I would like to ask you how do I disable Radium's mixins with my mod in a similar way to how Sodium and Canary allows me to disable the mixin. That way I can be sure this mixin doesn't break another mod's brushing automation code where they could construct their own EntityShapeContext and pass in a different item that the entity doesn't have.
https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json
https://discord.com/channels/104299991589199872/752308882969329684/1173607719433936996

**Comment by dima-dencep** [comment]
> how do I disable Radium's mixins

https://github.com/Asek3/Oculus/blob/1.20/src/main/resources/META-INF/mods.toml#L22-L25

```toml
[mods."lithium:options"]
"mixin.shapes.lazy_shape_context"=false
```
