### ISSUE TITLE
Radium breaks vanilla hoppers interaction with Create mod

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Reforged-Hub/radium-upstream#15]
### Version Information

radium-mc1.20.1-0.12.2+git.5f80f74.jar

### Expected Behavior

Contraptions should work and vanilla hopper behavior should be untouched.
Disabling this mod reverts behavior to vanilla (= hoppers work and don't ever get stuck).
Canary (canary-mc1.20.1-0.2.7.jar) does NOT cause this bug.

### Actual Behavior

Hoppers constantly get stuck during operation. Locking and unlocking them with redstone unstucks them, and they get stuck right after. Adding or removing items from them unstucks them, and they get stuck right after. Leaving and rejoining the world unstucks the hopper, and (you guessed it) they get stuck right after.
Both the hopper that goes into a Create mod belt and the one that feeds the deployers eventually get stuck and become useless. Create mod chutes are not affected by this bug.

### Reproduction Steps

1. I built [this machine](https://www.youtube.com/watch?v=68TciXvd6ac)
2. I added the required materials for the machine to start working
3. Increase the machine speed to 128 or 256 RPM. Not sure if it still bugs out on lower RPM.
4. All 4 hoppers will quickly get stuck and stop working until you keep manually updating them.

### Other Information

Minecraft log: https://api.paste.ee/p/IpkjO
Bug demonstration/proof: https://github.com/Reforged-Hub/radium-upstream/assets/25572454/b7d00bed-e9ca-4baf-b19e-341aa0a83093 (the machine itself was broken on the video but it was not the cause of the issue, I've 100% confirmed it and the bug is still clear on the video, please ignore the machine itself. And the comparator was off, not locking the hopper, and the top hoppers were stuck too)

### The irony

Just a funny comment, out of all 120 mods I'm using, including some in alpha and beta versions, the first and only one to actually break something was the only one that said "mod designed to improve [...] Minecraft without breaking things" lmao maybe you should reword your mod description or mark this as beta

**Comment by dima-dencep** [comment]
I don't know much about it, but...

https://github.com/Reforged-Hub/radium-upstream/assets/66722732/9da3c908-3def-43f5-bbc3-a13f5556aa38

**Comment by TBlazeWarriorT** [comment]
> I don't know much about it, but...
> 
> 
> 
> https://github.com/Reforged-Hub/radium-upstream/assets/66722732/9da3c908-3def-43f5-bbc3-a13f5556aa38
> 
> 
> 
> 

I don't think it bugs with just this, that's too simple.
My reproduction steps mention the whole machine is required, which isn't that big tbh.
It definitely bugs

**Comment by embeddedt** [comment]
@dima-dencep I'd guess it's caused by Lithium's hopper optimizations (`mixin.block.hopper`), as they make [many assumptions](https://github.com/Reforged-Hub/radium-upstream/blob/develop/src/main/java/me/jellysquid/mods/lithium/mixin/block/hopper/README.md) about inventories. It would be worthwhile to test with this disabled in Lithium's mixin properties file and possibly disable the option by default.

**Comment by TBlazeWarriorT** [comment]
> I don't know much about it, but...
> 
>  2023-12-27_22-00-04.1.mp4

Trying to reproduce my own bug was a bit trickier than I expected, I'll admit
I cloned my own machine *with the clone command* and it started working on the cloned one, it's kinda weird to trigger
But I've managed to reproduce the bug several times on the original machine (yet again)
It might have something to do with create's logic for making the belt "stuck" (too many items on it), but weirdly even the deployers at the top stop getting refilled from the hopper sometimes.
I wanted to share the world file but it was too big and messy

But one thing I can say for sure
@embeddedt is correct, and his solution (mixin.block.hopper=false) on the lithium.properties file makes the problematic machine work flawlessly
(and of course removing the flag and relaunching immediately breaks the machine again)
