### ISSUE TITLE
radium-0.8.2.jar

### ISSUE THREAD

**Issue by Sadamlucien** [Reforged-Hub/radium-upstream#17]
### Version

radium-0.8.2.jar
Minecraft version:1.19.2
Ferrite core:5.03
### Reproduction Steps

crashes together with ferrite core(5.0.3 and also older versions) 

### Crash Report File

[crash-2024-01-17_01.11.29-client.txt](https://github.com/Reforged-Hub/radium-upstream/files/13956581/crash-2024-01-17_01.11.29-client.txt)

**Comment by dima-dencep** [comment]
1.19.2 not supported
