### ISSUE TITLE
Breakdown of Double Chest Functionality

### ISSUE THREAD

**Issue by ShyCatsu** [Reforged-Hub/radium-upstream#19]
radium-mc1.20.1-0.12.2+git.5f80f74

Hopper should be able to pull from both sides of the chest. Refined storage should be able to view both halves of the double chest.

This doesn't happen.
![image_2024-02-03_071947174](https://github.com/Reforged-Hub/radium-upstream/assets/85979537/2bae848e-6109-4efc-a4e4-ced2cbdeea9a)

**Comment by muon-rw** [comment]
Seems to be caused by `mixin.world.block_entity_ticking.sleeping`

**Comment by ShyCatsu** [comment]
> Seems to be caused by `mixin.world.block_entity_ticking.sleeping`

YES! THAT IS IT! 

Since it disables key vanilla features, making even the most basic auto-smelter totally non-functional, is this a feature that could be fixed, or at least have chests as an exception?

Or if not, could the properties default be adjusted to have the default set to "false" for future updates, to avoid bugs like this happening in the future?

**Comment by embeddedt** [comment]
Does disabling `mixin.block.hopper` but leaving sleeping enabled also fix this?

**Comment by muon-rw** [comment]
We already had mixin.block.hopper disabled, so no.
