### ISSUE TITLE
[1.20.1] Radium is throwing errors in the logs

### ISSUE THREAD

**Issue by 630R63** [Reforged-Hub/radium-upstream#2]
### Version Information
radium-mc1.20-0.11.2
forge 47.1.44

### Expected Behavior
Was expecting the mod to function properly

### Actual Behavior
I don't know how serious this issue is, but I see errors in the logs such as this:
https://paste.gg/p/anonymous/3a60e21a885d4af0bdfb9139fd9d0370

### Reproduction Steps
1. Use radium-mc1.20-0.11.2.jar on a dedicated server
2. Just play normally on the server (this isn't happening all the time, so it can take a while for the error to appear. I also don't know what the player was doing when this issue occurred. I might come back to this when I have more details) 
3. Observe the logs

**Comment by MrRagtime** [comment]
I mean the mod page on [modrinth](https://modrinth.com/mod/radium) does say it is a Canary build as of now, but I don't know why they didn't say anything and just closed.
