### ISSUE TITLE
Chunk generation speed is very slightly slower than Canary

### ISSUE THREAD

**Issue by DarthCaesium** [Reforged-Hub/radium-upstream#20]
Hi! I've tested out both Canary and Radium in a modded instance with 150-ish mods (some of them performance mods). It seems that Radium is like 5% slower in chunk generation overall when compared to Canary, but it is faster at generating the exact chunks that are ahead of the player (e.g. when flying around in Creative and/or with Elytra) and has no associated chunk generation lag on FPS or TPS, which Canary has a problem with. Just letting you know, cause it seems like a potentially easy fix.

**Comment by DarthCaesium** [comment]
Sorry if this is confusing, but this was genuinely happening to me. Overall, it's very slightly slower at loading whole batches of chunks, but it seems to be faster at loading them individually. It's a weird observation, but I'd rather not have to have any chunk generation loading speed issues just because I use a much less broken mod that gives better performance than Canary.

**Comment by dima-dencep** [comment]
You have not provided a profiler of the spark or JVM

**Comment by DeshiDesu** [comment]
OP source: trust me
