### ISSUE TITLE
[1.20.1] Crash with REI

### ISSUE THREAD

**Issue by Starexify** [Reforged-Hub/radium-upstream#27]
### Version

>  radium-mc1.20.1-0.12.3+git.e2cf570

### Reproduction Steps

> 1. Download mod
> 2. Launch it with the latest version of REI 

### Crash Report File

> [latest.log](https://github.com/Reforged-Hub/radium-upstream/files/14815480/latest.log)
> [crash-2024-03-31_14.05.09-client.txt](https://github.com/Reforged-Hub/radium-upstream/files/14815493/crash-2024-03-31_14.05.09-client.txt)

### Additional Information

>

**Comment by dima-dencep** [comment]
Mod roughlyenoughitems requires cloth_config 10.0 or above
