### ISSUE TITLE
[1.20.1] Crash with latest version of Artifacts

### ISSUE THREAD

**Issue by Starexify** [Reforged-Hub/radium-upstream#28]
### Version

>  radium-mc1.20.1-0.12.3+git.e2cf570

### Reproduction Steps

> 1. Download mod
> 2. Launch it with the latest version of Artifacts.

### Crash Report File

> [latest.log](https://github.com/Reforged-Hub/radium-upstream/files/14815856/latest.log)

### Additional Information

> I get only a latest log. Nothing more. On their own the mods work. But together they crash
> Mod list:
architectury-9.2.14-forge
artifacts-forge-9.3.0
cloth-config-11.1.118-forge
curios-forge-5.7.2+1.20.1
radium-mc1.20.1-0.12.3+git.e2cf570

**Comment by dima-dencep** [comment]
What an understandable log! I think I'll just close this issue

**Comment by Starexify** [comment]
> What an understandable log! I think I'll just close this issue

Try yourself if you want. You will get the same thing. I literally even said "I get only a latest log. Nothing more."

**Comment by dima-dencep** [comment]
Looking at your past issue, I don't see the point in trying it

**Comment by Starexify** [comment]
> Looking at your past issue, I don't see the point in trying it

So you think if I just thought REI breaks because that's literally what happened for many startups. Then somehow minecraft made it work. Then I tried again and add it to 100 mods, crashes and then search through them. Removing each of them. Then finding Radium and Artifacts crash together that I have no clue?
