### ISSUE TITLE
Crash with Artifacts

### ISSUE THREAD

**Issue by SailHatan** [Reforged-Hub/radium-upstream#29]
### Version
Radium 0.12.3 for 1.20.14

### Reproduction Steps
1) Launch game with Radium 0.12.3 and Artifacts 9.3.0 along with their requirements
Modlist: 
  [✔] architectury-9.2.14-forge
  [✔] artifacts-forge-9.3.0
  [✔] cloth-config-11.1.118-forge
  [✔] curios-forge-5.7.2+1.20.1
  [✔] radium-mc1.20.1-0.12.3+git.e2cf570
### Crash Report File
[Log](https://hst.sh/koludevigi.sql)

**Comment by Looxond** [comment]
Same issue here is my log: https://mclo.gs/8RIHKOV

**Comment by dima-dencep** [comment]
@embeddedt
This bug resulted from the merging of one of your PRs

**Comment by dima-dencep** [comment]
As a temporary fix, you can put `mixin.entity.collisions.fluid=false` inside lithium.properties
