### ISSUE TITLE
[mod compat] Add DoesPotatoTick workaround

### ISSUE THREAD

**Issue by Cixon** [Reforged-Hub/radium-upstream#3]
**Is your feature request related to a problem? Please describe.**
Not really, radium is fairly smooth but I'd like to get maxium tps performance with DoesPotatoTick too.

**Describe the solution you'd like**
For Radium to only kick into gears when entities are loaded with DoesPotatoTick installed.

**Describe alternatives you've considered**
Disable mixin AI from Radium but this kinda defeats mods purpose. These two mods cannot coexist _currently_.

**Additional context**
It would be nice for these two mods to be interchangeable when loaded together. Both mods offer a great deal of value on servers with massive farms; its just a shame that currently the only way these two can work is to have a hallowed out Radium.

**Comment by Cixon** [comment]
Mod in question:
https://www.curseforge.com/minecraft/mc-mods/doespotatotick

Radium I used (0.11.2):
https://www.curseforge.com/minecraft/mc-mods/radium-reforged/files/4755208

**Comment by dima-dencep** [comment]
We won't do compatibility with "weird" mods, sorry

**Comment by Cixon** [comment]
> We won't do compatibility with "weird" mods, sorry

elaborate how this is “weird”? not very optimistic of you

**Comment by dima-dencep** [comment]
And why do you think DoesPotatoTick is a good mod and we should strive for compatibility with it?

**Comment by Cixon** [comment]
there’s a variety of reasons. both mods excel in positive tps performance effortlessly and mostly out the box.

dpt is just a great utility for servers in general and makes sense i mean, why tick entities you can’t even reach let alone render? then for the entities that are loaded, it’d be convenient for Radium to take over.

it simply doesn’t make sense for vanilla minecraft to have the server stress over unnecessary things like that. although the goal of radium is to reduce the stress/optimize it, there’s nothing wrong with enjoying both mods.

not to mention, both mods are both moderately popular, what other reason do u need?
