### ISSUE TITLE
Players are able to pass through the world border when Radium + Alex's Caves are both installed

### ISSUE THREAD

**Issue by etherealgears** [Reforged-Hub/radium-upstream#31]
### Version Information

MC Version: 1.20.1
Forge Version: 47.2.21
Mod Version: Radium 0.12.3 for 1.20.1

### Expected Behavior

The world border in Minecraft should be impassable, and players should be unable to move beyond the 29 999 983 coordinate.

### Actual Behavior

Players can walk through the world border all the way up to the 29 999 999 coordinate.

### Reproduction Steps

> 1. Travel to the world border.
> 2. Walk up to the world border at 29 999 983 (positive or negative on either the x or z axis).
> 3. Walk through it up to 29 999 999, which shouldn't be possible.

### Other Information

This bug only occurs when Radium is installed alongside Alex's Caves. As a sidenote, the same thing happens if Canary, the other Lithium port, is installed alongside Alex's Caves. Simply removing either Radium (or Canary) or Alex's Caves is enough to make the bug go away. The bug only happens when the two mods are installed together. I've tried this in a pack with no other mods installed besides these two. This bug has been reported to the Alex's Caves github by another person back in December, but since Radium was very recently updated and it still persists, I thought it might be a good idea to mention it here too.

**Comment by etherealgears** [comment]
I'm not a very experienced github user, so I'm not sure what it means that the question label has been added to this? Is there some info missing in my original issue I need to add?

**Comment by Vinzound** [comment]
The last game I had with those two mods, the Farseer miniboss from Alex's Mobs did not appear when I reached the farlands, not if this bug also has anything to do with this.

**Comment by rafaelkai** [comment]
I have none of these issues when using Radium default settings. Alex Mobs' Farseers also spawn correctly.
