### ISSUE TITLE
Crash with accessories

### ISSUE THREAD

**Issue by fg1989** [Reforged-Hub/radium-upstream#34]
### Version

> Forge 1.20.1-47.3.5
> Radium 0.12.3-hotfix for 1.20.1
> Accessories Neoforge 1.0.0 Alpha 24 for 1.20 (https://www.curseforge.com/minecraft/mc-mods/accessories/files/5456983)
> Cloth Config API [Forge 1.20(.1)] v11.1.118 (https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/4973441)

### Reproduction Steps

> Start the game (the game crashes on start)

### Crash Report File

> The game crashes on start but does not generate a file in the "crash-reports" folder

### Additional Information

> Game starts correctly if radium is not installed
> Even if all lithium optimizations are disabled by the configuration file, the game crashes on startup

(configuration file used)

```
# This is the configuration file for Radium.
# This file exists for debugging purposes and should not be configured otherwise.
#
# You can find information on editing this file and all the available options here:
# https://github.com/jellysquid3/lithium-fabric/wiki/Configuration-File
#
# By default, this file will be empty except for this notice.

mixin.ai=false
mixin.alloc=false
mixin.block=false
mixin.chunk=false
mixin.collections=false
mixin.entity=false
mixin.gen=false
mixin.math=false
mixin.shapes=false
mixin.world=false

mixin.cached_hashcode=false
mixin.experimental=false
mixin.profiler=false
mixin.util=false
```

**Comment by dima-dencep** [comment]
Everything works fine.

**Comment by Dragon-Seeker** [comment]
I would like to chim in stating that I can reproduce the issues as stated [here](https://github.com/wisp-forest/accessories/issues/67) and it comes down to NanoLiveConfig check for FabricLoader just checking if the base event module for FAPI is present which seems to have changed within later versions but not within the latest version of radium for 1.20.1 gotten from curseforge

**Comment by dima-dencep** [comment]
Everything worked in older versions of accessories, I thought it was a skills issue.

**Comment by diefesson** [comment]
Hey @fg1989  and anyone who stumbles with this problem.

I faced the same problem, but oddly enough, I fixed it by adding [connector](https://modrinth.com/mod/connector) and [forgified-fabric-api](https://modrinth.com/mod/forgified-fabric-api)  to my modpack.

Apparently, given some unknown condition, some mod tries to access Fabric API classes in a NeoForge enviroment resulting in a ClassNotFoundException

**Comment by Dragon-Seeker** [comment]
@diefesson Its an issues specific to mods using the version of [CaffinieConfig(NanoLiveConfig)](https://github.com/dima-dencep/NanoLiveConfig/pull/2) that has an improper way of checking for Fabric Loader that needs to be pulled and an update made for such that has yet tot occur. However the above method dose fix the issue temporarily for 1.20.1.

**Comment by diefesson** [comment]
I want to point out that other mods are also checking for FAPI in a similar way and many people facing the problem will also end up here. So it's still a valuable knowledge for those.

**Comment by dima-dencep** [comment]
Working on it!!!
