### ISSUE TITLE
1.21 NeoForge

### ISSUE THREAD

**Issue by amzelee** [Reforged-Hub/radium-upstream#36]
Just as the title says. As of right now Sodium has ported over to NeoForge. Unfortunately Lithium seems to be holding off on this and no statements have been made. Would be amazing if Radium becomes available for 1.21, but no pressure. Just here to make a request. Thank you for reading and have a nice day.

**Comment by 1foxy2** [comment]
you can use foxium in 1.21.1 https://www.curseforge.com/minecraft/mc-mods/foxium
