### ISSUE TITLE
Radium 1.21.1 crash on launch

### ISSUE THREAD

**Issue by amzelee** [Reforged-Hub/radium-upstream#38]
### Version
- [0.13.0a for 1.21.1](https://modrinth.com/mod/radium/version/0.13.0a)
### Reproduction Steps
1. Install Radium, Sodium, Sodium Extras.
2. Launch the game.
3. Game crashes.
### Crash Report File
- Crash Log
- [Latest Log](https://mclo.gs/zLGrUh9)
### Additional Information
Crashes when Sodium Extras is included. Launches fine when Extras is removed. Also launches fine when Radium is removed.

**Comment by dima-dencep** [comment]
It's a sodiumextra issue
