### ISSUE TITLE
Breaks NeoForges Creative Flight attribute

### ISSUE THREAD

**Issue by WhitePhant0m** [Reforged-Hub/radium-upstream#39]
### Version Information
radium-mc1.21.1-0.13.0a+git.f597bd8

### Expected Behavior
Not breaking NeoForges Creative Flight attribute

### Actual Behavior
Breaks NeoForges Creative Flight attribute

### Reproduction Steps
Run `/attribute @s neoforge:creative_flight base set 1`
Notice how you can't fly

**Comment by dima-dencep** [comment]
Do you know which radium optimization does this?
