### ISSUE TITLE
Crash on neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [Reforged-Hub/radium-upstream#40]
- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- ye
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.
- ye

------------------------

### Version

0.13.0b

### Reproduction Steps
just put the mod and sodium mods ig?

### Crash Report File
https://mclo.gs/whVGngD

**Comment by dima-dencep** [comment]
duplicate of #38
