### ISSUE TITLE
incompatibility with minecolonies

### ISSUE THREAD

**Issue by Lion010101** [Reforged-Hub/radium-upstream#42]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **bug report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version Information

> Launcher Version 1.21.1 Neoforge - 21.1.57
> radium-mc1.21.1-0.13.0a+git.f597bd8.jar
> minecolonies-1.1.705-1.21.1-snapshot.jar
> should auto install all of minecolonies library mods.

### Expected Behavior

> Not to crash when i place down any building from minecolonies

### Actual Behavior

> when placing down any building from minecolonies it will crash wihtout any error codes atall

### Reproduction Steps

> craft a Supply Camp
> click the ground with it and select a style
> after that the game will come up saving world and crash

> Example:
>trying to place anything from minecolonies will result in a crash.

### Other Information

> Latest.log will be below to help solve the issue.

[latest.log](https://github.com/user-attachments/files/17081300/latest.log)

**Comment by dima-dencep** [comment]
I don't see any radium related issues in the log.

**Comment by Lion010101** [comment]
o it was a radium issue cuse when i removed that mod it started working just fine but ok...

**Comment by Lion010101** [comment]
nvm it was on minecolonies end sorry for bothering u 👍
