### ISSUE TITLE
The villagers are broken

### ISSUE THREAD

**Issue by aphfug** [Reforged-Hub/radium-upstream#5]
### Version Information

Radium mc1.19.2-0.8.2

### Expected Behavior

The villagers should become librarian, sleep at night and be scared of the zombie.

### Actual Behavior

They don't do anything. Their AI is broken

### Reproduction Steps

Place a villager next to a bed at night

### Other Information

here's the list of all the other mods :

- AutoRegLib-1.8.2-55.jar
- balm-forge-I.19.2-4.6.0.jar
- chisels-and-bits-for e-l.3.142.jar
- CodeChickenLib- 1.19.2-4.3.1.481-universal.jar
- craftingtweaks-forge-1.19.2-15.1.8.jar
- create-1.19.2-0.5.1.e.jar
- curios-forge-1.19.2-5.1.4.1.jar
- elevatorid-1.19.2-1.8.9.jar
- EnderStorage-1.19.2-2.10.1.181 -universal.jar
- forbidden_arcanus- 1.19.2-2.1.3.jar
- ImmediatelyFast-1.2.6+1.19.2.jar
- jei-1.19.2-forge-11.6.0.1018.jar
- justzoom_forge_1.0.1-1_MC_1.19.jar
- konkrete_forge_1.6.1 _MC_1.19-1.19.2.jar
- Quark-3.4-409.jar
- radium-0.8.2.jar
- radon-0.8.2.jar
- reforgium-1.0.12a.jar
- rubidium-mc1.19.2-0.6.2c.jar
- shutupexperimentalsettings-1.0.5.jar
- sophisticatedbackpacks-1.19.2-3.18.58.907.jar
- StorageDrawers-1.19-11.1.2.jar
- TerraBlender-forge-1.19.2-2.0.1.136.jar
- twilightforest-1.19.2-2.0.1.136.jar
- valhesia_core-forge-1.19.2-11.4.1.jar
- waystones-forge-1.19.2-11.4.1.jar

Here's a video : https://youtu.be/8JydRl4Hujg
And of course it works with those mods without radium
[latest.log](https://github.com/Reforged-Hub/radium-upstream/files/12853205/latest.log)

**Comment by ToryXie** [comment]
I have the same problem. I only use Radium-0.12.0 for minecraft 1.20.1 and Rubidium-0.7.1 for minecraft 1.20.1.

Even when I use the summon command "/summon villager ~ ~ ~ {id:"minecraft:villager",VillagerData:{type:"savanna",profession:"librarian"}}", the librarian can't trade.

**Comment by dima-dencep** [comment]
This is a known bug and we are working on it, however versions below 1.20.1 will not be supported by radium
