### ISSUE TITLE
Villagers can't take jobs

### ISSUE THREAD

**Issue by victorguima** [Reforged-Hub/radium-upstream#8]
### Version Information

radium-0.8.2.jar

### Expected Behavior

Placing a work related block such as a lectern should result in the unemployed villager take the librarian job.

### Actual Behavior

Villagers are always unemployed no matter what

### Reproduction Steps

Create a new world and spawn a villager and put down a lectern, or you could find a village and place it there.

### Other Information

Only Radium Reforged loaded, forge version is 43.3.0 and Minecraft version 1.19.2

**Comment by embeddedt** [comment]
1.19.2 is not supported anymore.
